import { v4 as uuid } from "uuid";

export const hotels = {
    "categories": {
        "National Parks": [
            {
                id: uuid(),
                name: "Whispering Pines Cottages",
                image: "https://a0.muscache.com/im/pictures/miso/Hosting-26117817/original/9da40e3c-5846-4359-bb41-05c27b09a8f5.jpeg?im_w=720",
                address: "Jibhi",
                city: "Banjar Valley",
                state: "Himachal Pradesh",
                country: "India",
                price: 5999,
                rating: 4.7,
                numberOfBathrooms: 4,
                numberOfBeds: 2,
                numberOfguest: 6,
                numberOfToilets: 2,
                numberOfStudies: 0,
                hostName: "Daleep",
                hostJoinedOn: "March 2018",
                ameneties: ["Kitchen", "Wifi", "Pets Allowed"],
                healthAndSafety: ["Smoke alarm", "Carbon monoxide alarm"],
                houseRules: ["Check-in: 12:00 pm - 11:00 pm", "Check out: 11:00 am", "Pets are allowed"]
            },
            {
                id: uuid(),
                name: "Sukoon Baag",
                image: "https://a0.muscache.com/im/pictures/90d0b224-16e2-41c1-9819-6002749a193e.jpg?im_w=720",
                address: "Bir",
                city: "Joginder Nagar Valley",
                state: "Himachal Pradesh",
                country: "India",
                price: 3020,
                rating: "New",
                numberOfBathrooms: 2,
                numberOfBeds: 1,
                numberOfguest: 3,
                numberOfToilets: 1,
                numberOfStudies: 1,
                hostName: "Shashi",
                hostJoinedOn: "December 2019",
                ameneties: ["Kitchen", "Wifi", "Pets Allowed"],
                healthAndSafety: ["No Smoke alarm", "No Carbon monoxide alarm"],
                houseRules: ["Check-in: After 1:00 pm", "Check out: 11:00 am", "Pets are allowed"]
            },
            {
                id: uuid(),
                name: "Sooty's Hideout",
                image: "https://a0.muscache.com/im/pictures/miso/Hosting-614375154474735110/original/7e7f4c4a-c496-4844-bd02-44e276b41718.jpeg?im_w=720",
                address: "Shangarh",
                city: "HP",
                state: "Himachal Pradesh",
                country: "India",
                price: 2750,
                rating: "New",
                numberOfBathrooms: 3,
                numberOfBeds: 4,
                numberOfguest: 10,
                numberOfToilets: 3,
                numberOfStudies: 3,
                hostName: "Sankalp Avirjaan",
                hostJoinedOn: "May 2018",
                ameneties: ["Kitchen", "Wifi", "Pets Allowed"],
                healthAndSafety: ["No Smoke alarm", "No Carbon monoxide alarm", "Nearby lake, river, other body of water"],
                houseRules: ["Check-in: After 2:00 pm", "Check out: 11:00 am", "Pets are allowed", "No smoking", "No parties or events"]
            },
            {
                id: uuid(),
                name: "Indian Culture Hostel Deluxe Studio",
                image: "https://a0.muscache.com/im/pictures/miso/Hosting-596942733015239131/original/40481d9d-412c-4541-a030-946c1c43a968.jpeg?im_w=720",
                address: "Rishikesh",
                city: "Rishikesh",
                state: "Uttarakhand",
                country: "India",
                price: 2580,
                rating: 5.0,
                numberOfBathrooms: 3,
                numberOfBeds: 4,
                numberOfguest: 10,
                numberOfToilets: 3,
                numberOfStudies: 3,
                hostName: "Sankalp Avirjaan",
                hostJoinedOn: "May 2018",
                ameneties: ["Kitchen", "Wifi", "Pets Allowed"],
                healthAndSafety: ["No Smoke alarm", "No Carbon monoxide alarm", "Nearby lake, river, other body of water"],
                houseRules: ["Check-in: After 2:00 pm", "Check out: 11:00 am", "Pets are allowed", "No smoking", "No parties or events"]
            },
            {
                id: uuid(),
                name: "Stone Cottage",
                image: "https://a0.muscache.com/im/pictures/miso/Hosting-601816645157829673/original/e4792d54-354c-4187-854a-1d0552ecaa3e.jpeg?im_w=1200",
                address: "Jibhi",
                city: "Banjar Valley",
                state: "Himachal Pradesh",
                country: "India",
                price: 2499,
                rating: 4.60,
                numberOfBathrooms: 3,
                numberOfBeds: 4,
                numberOfguest: 10,
                numberOfToilets: 3,
                numberOfStudies: 3,
                hostName: "Sankalp Avirjaan",
                hostJoinedOn: "May 2018",
                ameneties: ["Kitchen", "Wifi", "Pets Allowed"],
                healthAndSafety: ["No Smoke alarm", "No Carbon monoxide alarm", "Nearby lake, river, other body of water"],
                houseRules: ["Check-in: After 2:00 pm", "Check out: 11:00 am", "Pets are allowed", "No smoking", "No parties or events"]
            },
            {
                id: uuid(),
                name: "Sun View Mountain",
                image: "https://a0.muscache.com/im/pictures/7428ed07-77e9-4f73-a0ae-4cb2d7b695a2.jpg?im_w=1200",
                address: "Kasol",
                city: "kasol",
                state: "Himachal Pradesh",
                country: "India",
                price: 925,
                rating: 4.86,
                numberOfBathrooms: 3,
                numberOfBeds: 4,
                numberOfguest: 10,
                numberOfToilets: 3,
                numberOfStudies: 3,
                hostName: "Sankalp Avirjaan",
                hostJoinedOn: "May 2018",
                ameneties: ["Kitchen", "Wifi", "Pets Allowed"],
                healthAndSafety: ["No Smoke alarm", "No Carbon monoxide alarm", "Nearby lake, river, other body of water"],
                houseRules: ["Check-in: After 2:00 pm", "Check out: 11:00 am", "Pets are allowed", "No smoking", "No parties or events"]
            },
        ],
        "Tiny Homes": [
            {
                id: uuid(),
                name: "RiverTree Duplex- Riverside Plantation TreehouseAC",
                image: "https://a0.muscache.com/im/pictures/c59d4481-f48a-43db-ade2-1df5689b725f.jpg?im_w=720",
                address: "Kottathara",
                city: "Wayanad",
                state: "Kerala",
                country: "India",
                price: 2580,
                rating: 5.0,
                numberOfBathrooms: 3,
                numberOfBeds: 4,
                numberOfguest: 10,
                numberOfToilets: 3,
                numberOfStudies: 3,
                hostName: "Sankalp Avirjaan",
                hostJoinedOn: "May 2018",
                ameneties: ["Kitchen", "Wifi", "Pets Allowed"],
                healthAndSafety: ["No Smoke alarm", "No Carbon monoxide alarm", "Nearby lake, river, other body of water"],
                houseRules: ["Check-in: After 2:00 pm", "Check out: 11:00 am", "Pets are allowed", "No smoking", "No parties or events"]
            },
            {
                id: uuid(),
                name: "RiverTree Duplex- Riverside Plantation TreehouseAC",
                image: "https://a0.muscache.com/im/pictures/c59d4481-f48a-43db-ade2-1df5689b725f.jpg?im_w=720",
                address: "Kottathara",
                city: "Wayanad",
                state: "Kerala",
                country: "India",
                price: 2580,
                rating: 5.0,
                numberOfBathrooms: 3,
                numberOfBeds: 4,
                numberOfguest: 10,
                numberOfToilets: 3,
                numberOfStudies: 3,
                hostName: "Sankalp Avirjaan",
                hostJoinedOn: "May 2018",
                ameneties: ["Kitchen", "Wifi", "Pets Allowed"],
                healthAndSafety: ["No Smoke alarm", "No Carbon monoxide alarm", "Nearby lake, river, other body of water"],
                houseRules: ["Check-in: After 2:00 pm", "Check out: 11:00 am", "Pets are allowed", "No smoking", "No parties or events"]
            },
            {
                id: uuid(),
                name: "RiverTree Duplex- Riverside Plantation TreehouseAC",
                image: "https://a0.muscache.com/im/pictures/c59d4481-f48a-43db-ade2-1df5689b725f.jpg?im_w=720",
                address: "Kottathara",
                city: "Wayanad",
                state: "Kerala",
                country: "India",
                price: 2580,
                rating: 5.0,
                numberOfBathrooms: 3,
                numberOfBeds: 4,
                numberOfguest: 10,
                numberOfToilets: 3,
                numberOfStudies: 3,
                hostName: "Sankalp Avirjaan",
                hostJoinedOn: "May 2018",
                ameneties: ["Kitchen", "Wifi", "Pets Allowed"],
                healthAndSafety: ["No Smoke alarm", "No Carbon monoxide alarm", "Nearby lake, river, other body of water"],
                houseRules: ["Check-in: After 2:00 pm", "Check out: 11:00 am", "Pets are allowed", "No smoking", "No parties or events"]
            },
        ]
    }   
    
}